# -*- coding: utf-8 -*-
"""7_3__2ChatBot1.ipynb""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KO3BRZkoq9n9hY_YpsJYP3onBolh9UY
"""

!pip install --upgrade certifi

!pip install pyTelegramBotAPI

import telebot

!pip  install gigachat

from google.colab import drive
drive.mount('/content/drive')

"""# Новый раздел"""

from gigachat import GigaChat
import ssl

def gpt_reauest(text):
  ssl_c = ssl.create_default_context()
  ssl_c.check_hostname = False
  ssl_c.verify_mode = ssl.CERT_NONE
  giga = GigaChat(
      credentials = open('gg.txt').read(),
      scope = 'GIGACHAT_API_PERS',
      model = 'Gigachat',
      verify_ssl_certs = False
  )
  answer = giga.chat(text)
 # print(answer.choices[0].message.content)
  return answer.choices[0].message.content

import certifi


import httpx
import ssl

# Для Linux/Windows/Mac пути могут отличаться
ssl_context = ssl.create_default_context()
ssl_context.load_default_certs()  # Загружает системные сертификаты
print(certifi.where())  # Покажет путь к файлу с корневыми сертификатами

"""# Новый раздел"""

!pip install mathgenerator

"""# Новый раздел"""

main_menu = {
    'btn1':'Расписание',
    'btn2':'ДЗ',
    'btn3':'Фото',
    'btn4':'Вопрос GigaChat',
    'btn5':'F.A.Q.',
    'btn6':'Игра в математику',
    'btn7':'Начать обучение',
    'btn8':'Начать тестирование'
}
question_menu = {
    'btn1':'Сколько будет 2+2?',
    'btn2':'Адрес школы',
    'btn3':'Работа баскетбольной площадки',
    'btn4':'-',
    'btn5':'-'
}

lessons = {
    'Урок 1':'Уроки\Урок 1',
    'Урок 2':'Уроки\Урок 2',
    'Урок 3':'Уроки\Урок 3',
    'Урок 4':'Уроки\Урок 4',
    'Урок 5':'Уроки\Урок 5'
}

"""# Новый раздел"""

import telebot
from telebot import types
import pickle
import os
from mathgenerator import mathgen
import random

bot = telebot.TeleBot('8430625002:AAG83jtgQRWwsEnKV6y1gJASw6oOqm_BJlM')

user_progres = {}
math_levels = [[1,2],[3,4],[5,6]]
questions = []

# Главное меню

btn_info = types.KeyboardButton('📋 Об ОГЭ')
btn_schedule = types.KeyboardButton('📅 Расписание')
btn_topics = types.KeyboardButton('📚 Пройденные темы')
btn_zap = types.KeyboardButton('📝 Записаться')
btn_pay = types.KeyboardButton('💳 Оплатить занятие')
btn_questions = types.KeyboardButton('❓ Частые вопросы')
btn_menu = types.KeyboardButton('Меню')
btn_1 =types.KeyboardButton('Игра в математику')
btn_2 =types.KeyboardButton('Начать обучение')
btn_3 =types.KeyboardButton('Начать тестирование')


lessons = {
    'Урок 1':'/content/Уроки/Урок 1',
    'Урок 2':'/content/Уроки/Урок 2',
    'Урок 3':'/content/Уроки/Урок 3',
    'Урок 4':'/content/Уроки/Урок 4',
    'Урок 5':'/content/Уроки/Урок 5'
}

def load_user_data(): #загрузка данных из файла
    if os.path.exists('user_data.pkl'):
        with open('user_data.pkl', 'rb') as f:
            return pickle.load(f)
    return {}

def save_user_data(data):#выгрузка данных в файл
    with open('user_data.pkl','wb') as f:
        pickle.dump(data, f)

def is_user_registered(user_id): #проверка, что пользователь зарегестрирован
    user_data = load_user_data()
    if str(user_id) in list(user_data.keys()):
        return True
    else:
        return False

def show_menu(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    markup.add(btn_info, btn_schedule, btn_topics, btn_zap, btn_pay, btn_questions,btn_1,btn_2,btn_3)
    bot.send_message(message.from_user.id, "Выберите действие:", reply_markup=markup)

def math_game(message):
    if message.text == 'Меню':#Возврат в меню по желаению пользователя
        show_menu(message)
        return
    user_id = str(message.from_user.id)
    global user_progres
    user_progres[user_id] = [0,0,'']
    markup_line = types.InlineKeyboardMarkup()
    level_math = load_user_data()[user_id]['level_math']#берём данные уровня математики
    problem, answer = mathgen.genById(math_levels[level_math][random.randint(0,len(math_levels[level_math])-1)])
    problem = problem.replace(r'\cdot','*').replace('$','')
    answer = answer.replace('$','')
    corr = random.randint(0,3)
    for i in range(4):
        _, fake = mathgen.genById(math_levels[level_math][random.randint(0,len(math_levels[level_math])-1)])
        fake = fake.replace('$','')
        btn = types.InlineKeyboardButton(
            text = f'{answer if i==corr else fake}',#если i и corr равны, пишется answer, иначе fake
            callback_data=f'math_{i}_{corr}_{problem}'
        )
        markup_line.add(btn)
    msg = bot.send_message(user_id, f'Решите пример {problem}', reply_markup=markup_line)
    user_progres[user_id][2] = msg.message_id


def lesson_selection(message):
    if message.text == 'Меню': #если пользователь нажал меню - возвращаемся
        show_menu(message)
        return
    lesson = message.text #считываем урок, который ползователь выбрал
    lesson_folder = lessons[lesson] #считываем путь к конкретной папке
    try:
        send_materials(message,lesson_folder)
        bot.send_message(message.chat.id, f'Файлы урока {lesson} успешно отправлены')
    except BaseException:
        bot.send_message(message.chat.id, 'Ошибка при отправке файлов')
    show_menu(message)

def send_materials(message, folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        if filename.endswith('.txt'):
            with open(file_path, 'r', encoding='utf-8') as file:
                bot.send_message(message.from_user.id, f"Текст урока {file.read()}")
        elif filename.endswith(('.jpg','.jpeg','.png')):
            with open(file_path, 'rb') as photo:
                bot.send_photo(message.from_user.id,photo)
        elif filename.endswith(('.mp4','.mov')):
            with open(file_path, 'rb') as video:
                bot.send_video(message.from_user.id,video)
        elif filename.endswith('.pdf'):
            with open(file_path, 'rb') as pdf:
                bot.send_document(message.from_user.id,pdf, caption='Учебный файл')
        elif filename.endswith('.mp3'):
            with open(file_path, 'rb') as audio:
                bot.send_document(message.from_user.id,audio, caption='Аудио файл')
                #можно использовать также bot.send_audio()
def test_mode(message):
    if message.text == 'Меню': #если пользователь нажал меню - возвращаемся
        show_menu(message)
        return
    global questions, user_progres
    user_id = str(message.from_user.id)
    user_progres[user_id] = [0,0,'']
    markup = types.ReplyKeyboardMarkup()
    markup.add('Меню')
    lesson_name = list(lessons.keys())[int(message.text)-1]
    bot.send_message(user_id, f"Начинает тест по уроку {lesson_name}",reply_markup=markup)
    try:
        questions = open('/content/test_'+str(message.text)+'.txt','r',encoding='utf-8').readlines()
    except BaseException:
        bot.send_message(user_id,'Ошибка чтения файла')
        show_menu(message)
        return
    send_question(message, questions[user_progres[user_id][0]])

def send_question(message, question):
    markup = types.InlineKeyboardMarkup()
    parts = question.split('_')
    user_id = str(message.from_user.id)
    #Сколько будет 2+2?_1_2_3_4_3
    #В переменной parts получим список ['Сколько..','1','2','3','4','3']
    for i, answer in enumerate(parts[1:-1]):
        btn = types.InlineKeyboardButton(
            text = answer,
            callback_data=f'answer_{user_progres[user_id][0]}_{i}_{parts[-1]}'
        )
        markup.add(btn)
    msg = bot.send_message(user_id, f'{user_progres[user_id][0]+1}. Вопрос {parts[0]}',reply_markup=markup)
    user_progres[user_id][2] = msg.message_id
@bot.callback_query_handler(func=lambda call: call.data.startswith("answer_"))
def handle_answer(message):
    _,ques,answ,corr = message.data.split('_')
    user_id = str(message.from_user.id)
    bot.edit_message_text(
        chat_id=user_id,
        message_id=user_progres[user_id][2],
        text=f'{ques} \nНомер ответа - {int(answ)+1}',
        reply_markup=None
    )
    user_progres[user_id][0]+=1
    if int(answ) == int(corr):
        user_progres[user_id][1]+=1
    if user_progres[user_id][0] != len(questions):
        bot.send_message(user_id, 'Следующий вопрос')
        send_question(message, questions[user_progres[user_id][0]])
    else:
        bot.send_message(user_id, 'Тест завершён!')
        bot.send_message(user_id, f'Ты правильно ответил на {user_progres[user_id][1]}'
                         f' из {len(questions)} вопросов')
        user_data = load_user_data()
        score = round(user_progres[user_id][1]*100/len(questions),2)
        if score >= 60:
            user_data[user_id]['level']+=1
            bot.send_message(user_id, 'Вы прошли тест по этому модулю')
        else:
            bot.send_message(user_id, 'Вы не прошли тест, попробуйте снова')
        save_user_data(user_data)
        show_menu(message)

@bot.callback_query_handler(func=lambda call: call.data.startswith('math_'))
#срабатывает когда пользователь отправляет ответ на мат. пример
def math_answer(message):
    _,answ,corr,problem = message.data.split('_')
    user_id = str(message.from_user.id)
    bot.edit_message_text(
        chat_id=user_id,
        message_id=user_progres[user_id][2],
        text=f'Пример {problem}, ваш ответ №{answ}',
        reply_markup=None
    )
    user_data = load_user_data()
    user_id = str(message.from_user.id)
    if corr==answ:
        user_data[user_id]['score_math']+=1
        if user_data[user_id]['score_math']>=5:
            if user_data[user_id]['level_math'] <2:
                user_data[user_id]['level_math']+=1
            user_data[user_id]['score_math']=0
        save_user_data(user_data)
        bot.send_message(user_id,'Правильно!')
    else:
        bot.send_message(user_id,'Не правильно!')
    msg = bot.send_message(user_id,f'Начать снова? Ваши очки - {user_data[user_id]["score_math"]}'
                           f', ваш уровень - {user_data[user_id]["level_math"]}')
    bot.register_next_step_handler(msg, math_game)


# Данные для оплаты
PAYMENT_DATA = {
    'sber': {
        'name': 'Сбербанк',
        'phone': '89806505637',  # Номер для переводов
        'pay_link': 'https://www.sberbank.com/sms/pbpn?requisiteNumber=79806505637',
        'qr_code_path': 'QRsber.jfif',
        'amount': 1000,
        'has_qr': True
    },
    'tinkoff': {
        'name': 'ТБанк',
        'phone': '89806505637',  # Замените на реальный номер
        'amount': 1000,
        'has_qr': False
    },
    'vtb': {
        'name': 'ВТБ',
        'phone': '89806505637',  # Замените на реальный номер
        'amount': 1000,
        'has_qr': False
    },
    #'admin_phone': '79806505637'  # Номер администратора
    'admin_phone': '79109705122'  # Номер администратора
}

@bot.message_handler(func=lambda message: message.text == '💳 Оплатить занятие')
def handle_payment(message):
    markup = types.InlineKeyboardMarkup(row_width=1)
    btn_sber = types.InlineKeyboardButton("💙 Сбербанк (QR/номер)", callback_data='bank_sber')
    btn_tinkoff = types.InlineKeyboardButton("🟡 ТБанк (по номеру)", callback_data='bank_tinkoff')
    btn_vtb = types.InlineKeyboardButton("🔵 ВТБ (по номеру)", callback_data='bank_vtb')
    markup.add(btn_sber, btn_tinkoff, btn_vtb)

    bot.send_message(
        message.chat.id,
        "🏦 Выберите банк для оплаты:",
        reply_markup=markup
    )

@bot.callback_query_handler(func=lambda call: call.data.startswith('bank_'))
def process_bank_selection(call):
    bank_key = call.data.split('_')[1]
    bank = PAYMENT_DATA[bank_key]

    if bank['has_qr']:
        send_sber_payment(call, bank)
    else:
        send_simple_payment(call, bank)

def send_sber_payment(call, bank):
    payment_text = f"""
💳 <b>Оплата через {bank['name']}</b>

1. <b>Способ 1:</b> Переведите на номер:
   <b>{bank['phone']}</b>

2. <b>Способ 2:</b> Перейдите по ссылке:
   {bank['pay_link']}

3. <b>Способ 3:</b> Отсканируйте QR-код ниже

После оплаты нажмите "Я оплатил"
"""

    markup = types.InlineKeyboardMarkup()
    btn_paid = types.InlineKeyboardButton("✅ Я оплатил", callback_data=f'confirm_{bank["name"]}')
    markup.add(btn_paid)

    try:
        bot.send_message(
            call.message.chat.id,
            payment_text,
            parse_mode='HTML',
            reply_markup=markup
        )

        if os.path.exists(bank['qr_code_path']):
            with open(bank['qr_code_path'], 'rb') as qr_file:
                bot.send_photo(
                    call.message.chat.id,
                    qr_file,
                    caption=f"📲 Отсканируйте QR-код в приложении {bank['name']}"
                )
        else:
            bot.send_message(
                call.message.chat.id,
                "⚠️ QR-код временно недоступен, используйте другие способы оплаты"
            )

        bot.delete_message(call.message.chat.id, call.message.message_id)

    except Exception as e:
        bot.send_message(
            call.message.chat.id,
            f"⚠️ Ошибка: {str(e)}. Используйте номер: {bank['phone']}"
        )

def send_simple_payment(call, bank):
    payment_text = f"""
💳 <b>Оплата через {bank['name']}</b>

1. Переведите <b>{bank['amount']} руб.</b> на номер:
   <b>{bank['phone']}</b>

2. В комментарии укажите:
   - ФИО ученика
   - Дату занятия

После оплаты нажмите "Я оплатил"
"""

    markup = types.InlineKeyboardMarkup()
    btn_paid = types.InlineKeyboardButton("✅ Я оплатил", callback_data=f'confirm_{bank["name"]}')
    markup.add(btn_paid)

    bot.send_message(
        call.message.chat.id,
        payment_text,
        parse_mode='HTML',
        reply_markup=markup
    )
    bot.delete_message(call.message.chat.id, call.message.message_id)

@bot.callback_query_handler(func=lambda call: call.data.startswith('confirm_'))
def confirm_payment(call):
    bank_name = call.data.split('_')[1]

    markup = types.InlineKeyboardMarkup(row_width=1)

    # Формируем правильные ссылки
    whatsapp_url = f"https://wa.me/{PAYMENT_DATA['admin_phone']}?text=Чек%20оплаты%20({bank_name})"
    telegram_url = f"https://t.me/+{PAYMENT_DATA['admin_phone']}"  # Или используйте @username если есть

    markup.add(
        types.InlineKeyboardButton("📲 Отправить в WhatsApp", url=whatsapp_url),
        types.InlineKeyboardButton("✉️ Отправить в Telegram", url=telegram_url)
    )

    instruction = f"""
📨 <b>Отправьте чек администратору</b>

1. Нажмите кнопку ниже
2. Отправьте скриншот чека
3. Укажите:
   - ФИО ученика
   - Дату занятия
   - Сумму оплаты
   - Банк: {bank_name}

<b>Важно:</b> Если кнопка Telegram не работает, напишите напрямую на номер:
{PAYMENT_DATA['admin_phone']}
"""

    try:
        bot.send_message(
            call.message.chat.id,
            instruction,
            parse_mode='HTML',
            reply_markup=markup
        )
    except Exception as e:
        error_msg = f"""
⚠️ <b>Ошибка при отправке</b>

Пожалуйста, напишите напрямую на номер:
{PAYMENT_DATA['admin_phone']}

И укажите:
- ФИО ученика
- Дату занятия
- Сумму оплаты
- Банк: {bank_name}
"""
        bot.send_message(
            call.message.chat.id,
            error_msg,
            parse_mode='HTML'
        )


# Меню пройденных тем
topics_markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn_lesson1 = types.KeyboardButton('Урок 1: Алгебраические выражения')
btn_lesson2 = types.KeyboardButton('Урок 2: Геометрия треугольников')
btn_back = types.KeyboardButton('🔙 Назад')
topics_markup.add(btn_lesson1, btn_lesson2, btn_back)

# База знаний FAQ
FAQ = {
    # Об ОГЭ
    "формат экзамена": "ОГЭ по математике состоит из 2 модулей: Алгебра (17 задач) и Геометрия (9 задач). Всего 26 заданий (20 базовых, 6 повышенной сложности).",
    "дата экзамена": "Основной период ОГЭ в 2025 году: 20 мая. Резервные дни: 26 июня и 2 июля.",
    "сколько длится": "Экзамен длится 3 часа 55 минут (235 минут).",
    "минимальный балл": "Минимальный балл для сдачи - 8 (из 32 возможных).",
    "как оценивается": "Максимальный балл - 32. За модуль Алгебра - 20 баллов, за Геометрию - 12 баллов.",

    # О занятиях
    "стоимость": "Разовое занятие - 1 000 руб. Абонемент: 4 занятия - 3 000 руб, 8 занятий - 5 000 руб.",
    "сколько занятий": "Занятия проходят 1-2 раза в неделю. Можно выбрать удобный график.",
    "продолжительность занятия": "Обычное занятие длится 60 минут, интенсив - 90 минут.",
    "сколько человек в группе": "В группах 5-8 человек для эффективного обучения.",
    "можно индивидуально": "Да, возможны индивидуальные занятия. Стоимость - 1 500 руб/занятие.",

    # О преподавателях
    "кто преподает": "Занятия ведут опытные преподаватели с педагогическим образованием, эксперты ОГЭ и ЕГЭ по математике и информатике.",
    "опыт преподавателей": "Наши педагоги готовят к ОГЭ более 10 лет, средний балл учеников - 25+, являются экспертами ОГЭ и ЕГЭ по математике и информатике.",

    # О программе
    "какие темы": "Проходим всю школьную программу: алгебру, геометрию, теорию вероятностей.",
    "как строится программа": "Программа адаптируется под уровень группы. 70% времени - практика.",
    "сколько вариантов": "Разбираем более 10 типовых вариантов ОГЭ за курс. Варианты прошлых лет, Демоверсия и варианты СтатГрад.",
    "будет ли повторение": "Да, в конце курса - 2 недели на повторение сложных тем.",

    # О записи
    "как записаться": "Звоните +7 (910) 970-51-22 или пишите в WhatsApp или Telegram.",
    "нужна ли предоплата": "Да, для бронирования места в группе нужна предоплата 1000 руб.",
    "можно онлайн": "Да, есть онлайн-группы. Стоимость такая же.",

    # О материалах
    "нужны учебники": "Все материалы предоставляем бесплатно. Рекомендуем тетрадь 48 листов.",
    "даете ли задания": "Да, после каждого занятия - домашняя работа с проверкой.",
    "есть ли пробники": "Каждые 2 недели пишем пробный ОГЭ с разбором ошибок.",

    # Другие вопросы
    "скидки": "Скидка при оплате абонемента на 4 или 8 занятий в месяц. При покупке абонемента на полгода - скидка 10%.",
    "можно ли вернуть деньги": "При отмене за 2+ дня - занятие можно отработать с другой группой. При болезни - пропущенные занятия переносятся на следующий месяц (по справке).",
    "есть ли сертификат": "Да, по окончании курса выдается сертификат.",
    "когда начало": "Набор в группы идет постоянно. Можете оставить заявку - мы вас пригласим на пробное занятие.",

    # Дополнительные вопросы об ОГЭ
    "какие калькуляторы": "На ОГЭ разрешен только простой калькулятор без программируемых функций. Рекомендуем Casio FX-82.",
    "можно ли с телефоном": "Нет, телефоны и smart-часы запрещены. При обнаружении - удаление с экзамена.",
    "как подать апелляцию": "Апелляцию можно подать в течение 2 дней после объявления результатов в своей школе.",
    "сколько задач решить": "Для тройки нужно решить 8 задач, для четверки - 15, для пятерки - 22+. Обязательно минимум 2 балла по геометрии.",
    "какие справочные материалы": "Выдадут базовые формулы, но лучше их знать наизусть.",

    # Вопросы о подготовке
    "с чего начать подготовку": "Начните с диагностики пробелов. Мы проводим входное тестирование.",
    "сколько нужно готовиться": "Оптимально - 6-8 месяцев при 2 занятиях в неделю.",
    "можно успеть за месяц": "Да, но только интенсивный курс (4-5 занятий в неделю).",
    "какие самые сложные темы": "Чаще всего проблемы с геометрией (задачи на доказательство) и графиками.",
    "как быстро считать": "Даем специальные техники устного счета и алгоритмы решения.",

    # Вопросы о занятиях
    "можно поменять группу": "Да, можно перейти в другую группу при наличии свободных мест.",
    "есть ли перерыв": "Между занятиями - 10 минут перерыв. В интенсивах - 15 минут.",
    "можно с родителями": "Да, любое занятие можно посетить с родителем.",
    "есть ли видеоразборы": "Да, все пробники разбираем на видео и высылаем записи.",
    "как контролируют прогресс": "Раз в месяц - тестирование с подробным разбором ошибок.",

    # Вопросы о преподавателях
    "можно выбрать преподавателя": "Да, при записи можете указать предпочтения.",
    "есть ли молодые преподаватели": "Да, но все они проходят строгий отбор и стажировку.",
    "кто проверяет дз": "Домашние работы проверяет ваш преподаватель с комментариями.",
    "есть ли куратор": "Да, за каждой группой закреплен куратор для организационных вопросов.",
    "можно ли сменить преподавателя": "Да, можно перейти к другому преподавателю.",

    # Организационные вопросы
    "что брать на занятие": "Тетрадь, ручку, карандаш, линейку, сменную обувь. Остальное предоставим.",
    "есть ли гардероб": "Да, в обоих филиалах есть гардероб.",
    "где можно ожидать ребенка": "В холле есть зона ожидания с кулером и диванами. Но лучше пойти погулять.",
    "есть ли парковка": "У филиалов на Строителей и Урицкого есть бесплатные парковки.",
    "можно ли питаться": "В холле есть кулер с водой. Еду приносить можно в ланч-боксах. На первом этаже (Урицкого, 39) есть кафе.",

    # Технические вопросы
    "нужен ли компьютер": "Только для онлайн-занятий. Мы предоставляем все материалы.",
    "какая платформа для онлайн": "Используем ВКонтакте с интерактивной доской.",
    "если пропал интернет": "Запись занятия вышлем, деньги за занятие не сгорают.",
    "как получить материалы": "После занятия высылаем файлы в Telegram-чат группы.",
    "нужен ли принтер": "Нет, все материалы можно использовать в электронном виде.",

    # Вопросы о результатах
    "какой средний балл": "Средний балл наших учеников - 25 из 32.",
    "сколько пятерок": "В 2024 году 70% наших учеников получили пятерки.",
    "есть ли отзывы": "Да, на Яндекс.Картах 100+ реальных отзывов.",
    "можно ли посмотреть работы": "Да, храним все пробные работы до конца года.",
    "когда будут результаты": "Результаты пробников готовы через 3 дня с разбором ошибок."
}

@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.send_message(message.chat.id,"Привет! Я бот для подготовки к ОГЭ по математике от Клуба Знаний 🎓\n")
    if is_user_registered(message.from_user.id):
        bot.send_message(message.chat.id, 'Зарегестрирован')
        show_menu(message)
    else:
        bot.send_message(message.chat.id, 'Не зарегестрирован')
        Register_menu(message)
    # bot.send_message(message.chat.id, "Выберите действие:",
    #                  reply_markup=markup)

@bot.message_handler(commands=['register'])
def Register_menu(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    btn_phone = types.KeyboardButton('Отправить номер телефона', request_contact=True)
    markup.add(btn_phone)
    bot.send_message(message.chat.id, 'Просьба пройти регистрацию.\n\n'
                     '1. Нажмите на кнопку, чтобы отправить номер телефон\n'
                     '2. Затем введите ФИО', reply_markup=markup)

@bot.message_handler(content_types=['contact'])
def handle_contact(message):
   user_id = str(message.from_user.id)#получение ID пользователя
   phone = message.contact.phone_number #получаем номер телефона из сообщения, которое отправили
   user_data = load_user_data() #загружаем информацию о пользователях, которая уже есть
   if user_id not in user_data: #проверяем, что пользователя с таким ID нет
       user_data[user_id] = {} #если его нет, то добавляем в список пользователей
   user_data[user_id]['phone'] = phone #по ID пользователя добавляем поле номер телефона
   user_data[user_id]['level_math'] = 0  # Уровень в математике
   user_data[user_id]['score_math'] = 0  # Счет в математике
   user_data[user_id]['level'] = 0 #уровень урока, который пройден
   save_user_data(user_data) #сохраняем в файл полученную информацию
   bot.send_message(message.chat.id,'Вы зарегестрированы')
   show_menu(message)
#    msg = bot.send_message(message.chat.id, "Теперь введите ваше ФИО:")
#    bot.register_next_step_handler(msg, process_name_step)


@bot.message_handler(content_types=['photo'])
def photoes(message):
    file_id = message.photo[-1].file_id #из полученного сообщения берём фото.
    # ИД хранится в последнем элементе с помощью обращения к нему мы получаем file id
    file_info = bot.get_file(file_id) #получение информации о самом файле по его ID
    download_file = bot.download_file(file_info.file_path) #загузка файла в оперативную память
    with open('name_file.jpg', 'wb') as new_f: #сохранение файла
        new_f.write(download_file)
    bot.reply_to(message,'Фото сохранено') #отправка уведомления пользователю


@bot.message_handler(func=lambda message: message.text == '📚 Пройденные темы')
def show_lessons_menu(message):
    bot.send_message(message.chat.id,
                    "Выберите урок для просмотра материалов:",
                    reply_markup=topics_markup)

@bot.message_handler(func=lambda message: message.text in ['Урок 1: Алгебраические выражения',
                                                         'Урок 2: Геометрия треугольников'])
def send_lesson_info(message):
    if message.text == 'Урок 1: Алгебраические выражения':
        response = ("📚 <b>Урок 1: Алгебраические выражения</b>\n\n"
                    "📌 <b>Пройденные темы:</b>\n"
                    "- Преобразование выражений\n"
                    "- Формулы сокращенного умножения\n"
                    "- Разложение на множители\n\n"
                    "📝 <b>Домашнее задание:</b>\n"
                    "1. Учебник: стр. 45-48, №12-15\n"
                    "2. Рабочая тетрадь: стр. 22-25")
    else:
        response = ("📚 <b>Урок 2: Геометрия треугольников</b>\n\n"
                    "📌 <b>Пройденные темы:</b>\n"
                    "- Теорема Пифагора\n"
                    "- Признаки подобия\n"
                    "- Свойства медиан\n\n"
                    "📝 <b>Домашнее задание:</b>\n"
                    "1. Учебник: стр. 78-82, №8-12\n"
                    "2. Рабочая тетрадь: стр. 35-38")

    bot.send_message(message.chat.id, response, parse_mode='HTML')



@bot.callback_query_handler(func=lambda call: call.data.startswith('faq_'))
def handle_faq_categories(call):
    if call.data == 'faq_price':
        text = "💵 <b>Стоимость:</b>\n\n" + "\n".join(
            [v for k,v in FAQ.items() if 'стоимость' in k or 'абонемент' in k or 'оплата' in k])
    elif call.data == 'faq_schedule':
        text = "📅 <b>Расписание:</b>\n\n" + "\n".join(
            [v for k,v in FAQ.items() if 'расписание' in k or 'занятий' in k or 'начало' in k])
    else:
        text = "📝 <b>Запись:</b>\n\n" + "\n".join(
            [v for k,v in FAQ.items() if 'запис' in k or 'предоплат' in k or 'онлайн' in k])

    bot.edit_message_text(chat_id=call.message.chat.id,
                        message_id=call.message.message_id,
                        text=text,
                        parse_mode='HTML')



# Этот обработчик должен быть ПОСЛЕДНИМ
@bot.message_handler(func=lambda message: True)
def handle_all_messages(message):
    if message.text == '📋 Об ОГЭ':
      response = ("📌 <b>Основная информация об ОГЭ по математике:</b>\n\n"
                  "🔹 <b>Формат экзамена:</b>\n"
                  "2 модуля: Алгебра и Геометрия\n"
                  "26 заданий (20 базовых, 6 повышенной сложности)\n\n"
                  "🔹 <b>Продолжительность:</b> 3 часа 55 минут\n\n"
                  "🔹 <b>Минимальный балл:</b> 8 (из 32)\n\n"
                  "📅 <b>Даты проведения 2025:</b>\n"
                  "Основной период: 20 мая\n"
                  "Резервные дни: 26 июня, 2 июля")
      bot.send_message(message.chat.id, response, parse_mode='HTML')
    elif str(message.text).lower() == 'привет':
        bot.reply_to(message, "Привет!")
    elif message.text == 'Игра в математику':
       markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
       markup.add("Меню", "Начать!")
       msg = bot.send_message(
           message.chat.id,
           "Добро пожаловать в математический квиз\nнажмите начать",
           reply_markup=markup)
       bot.register_next_step_handler(msg, math_game)
    elif message.text == "Начать обучение":
        user_data = load_user_data()
        user_id = str(message.from_user.id)
        level = user_data[user_id]['level']#временно поставим зависимость от уровня математики

        #если хотите посмотреть все уроки, временно напишите level = 4
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        markup.add('Меню')
        avalible_lessons = list(lessons.keys())[0:level+1]#при таком обрезании списка - [0,2)
        for lesson in avalible_lessons:
            markup.add(types.KeyboardButton(lesson))
        msg = bot.send_message(user_id, 'Выберите урок для изучения',
                               reply_markup=markup)
        bot.register_next_step_handler(msg,lesson_selection)###

    elif message.text == 'Начать тестирование':
        user_data = load_user_data()
        user_id = str(message.from_user.id)
        level = user_data[user_id]['level']
        markup = types.ReplyKeyboardMarkup()
        for i in range(level+1):
            markup.add(f'{i+1}')
        markup.add('Меню')
        msg = bot.send_message(user_id,"Выберите тест для прохождения",
                               reply_markup=markup)
        bot.register_next_step_handler(msg, test_mode)


    elif message.text == '📅 Расписание':
      response = ("📅 <b>Расписание занятий:</b>\n\n"
                  "<b>Клуб Знаний на Урицкого, 39:</b>\n"
                  "ВТ: 17:00-18:00 (группа А)\n"
                  "<b>Клуб Знаний на Строителей, 15:</b>\n"
                  "Ср/Пя: 18:00-19:00 (группа С+В)\n"
                  "Сб: 16:00-17:00 (интенсив)")
      bot.send_message(message.chat.id, response, parse_mode='HTML')
    elif message.text == '📝 Записаться':
      response = ("📞 <b>Контакты для записи:</b>\n\n"
                  "Телефон: +7 (980) 970-51-22\n"
                  "WhatsApp: https://wa.me/79806505637\n\n"
                  "🏫 <b>Адреса:</b>\n"
                  "• Урицкого, 39 (главный офис)\n"
                  "• Строителей, 15 (новый филиал)\n\n"
                  "⏰ <b>Часы работы:</b> 10:00-19:00 ежедневно")

      markup = types.InlineKeyboardMarkup()
      btn_call = types.InlineKeyboardButton("📞 Позвонить", callback_data='call')
      btn_whatsapp = types.InlineKeyboardButton("WhatsApp", url='https://wa.me/79806505637')
      markup.add(btn_call, btn_whatsapp)

      bot.send_message(message.chat.id, response, parse_mode='HTML', reply_markup=markup)
    elif message.text == '🔙 Назад':
      show_menu(message)
    elif message.text == '❓ Частые вопросы':
      markup = types.InlineKeyboardMarkup()
      btn1 = types.InlineKeyboardButton("Стоимость", callback_data='faq_price')
      btn2 = types.InlineKeyboardButton("Расписание", callback_data='faq_schedule')
      btn3 = types.InlineKeyboardButton("Запись", callback_data='faq_signup')
      markup.add(btn1, btn2, btn3)

      bot.send_message(message.chat.id,
                   "Выберите категорию вопросов:",
                   reply_markup=markup)

    elif message.text == 'Меню':
      show_menu(message)
    else:
    # Если это не команда меню, ищем в FAQ
      text = message.text.lower()
      for keyword, answer in FAQ.items():
          if keyword in text:
              bot.reply_to(message, answer)
              return

    # Если вопрос не распознан
          else:
            bot.reply_to(message, "Извините, я не понял вопрос. Вы можете:\n"
                            "1. Переформулировать вопрос\n"
                            "2. Позвонить нам: +7 (910) 970-51-22\n"
                            "3. Выбрать раздел из меню")
            show_menu(message)
            return


bot.polling()